name: ricky_cli
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  pubspec: ">=2.0.1 <3.0.0"
  meta: ">=1.7.0 <2.0.0"
  recase: ">=4.0.0 <5.0.0"
  image: "^3.1.1"
  xml: ^5.3.1
  #  archive: ^3.1.2
  ansicolor: ">=2.0.1 <3.0.0"
  process_run: ">=0.12.2 <1.0.0"
  http: ">=0.13.4 <2.0.0"
  path: ">=1.8.0  <2.0.0"
  version: ">=2.0.0 <3.0.0"
  intl: ">=0.17.0 <1.0.0"
  cli_dialog: ">=0.5.0 <1.0.0"
  dart_style: ">=2.0.1 <3.0.0"
  yaml: ">=3.1.0 <4.0.0"
  collection: ">=1.15.0 <2.0.0"
  colorize: ^3.0.0
  enum_to_string: ^2.0.1
  antlr4: 4.9.3
  bitmap: ^0.1.2

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
